# Site settings
title: 阿仲的博客
email: Amy_zhjx@163.com
description: > # this means to ignore newlines until "baseurl:"
  前端开发程序媛
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://banyaner.github.io" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  Banyaner
# Build settings
markdown: kramdown
#plugins
port:    8080
host:    127.0.0.1