# Site settings
title: 阿仲的博客
email: Amy_zhjx@163.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "my-awesome-site" # the subpath of your site, e.g. /blog/
url: "https://bannyaner.github.io" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  Banyaner

# Build settings
markdown: kramdown
#plugins
